version: '3.5'

networks:
  acc-service-net:
    driver: bridge

volumes:
  dbdata6:

services:
  acc-service:
    container_name: acc-service
    image: acc-service
    ports:
      - "8080:8080"
    networks:
      - acc-service-net
    restart: on-failure

  mongodb:
    container_name: mongodb
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - acc-service-net
